language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

sudo: false

env:
  CODECLIMATE_REPO_TOKEN: e22c15a3c0c76152f3123cc37c9b4084402d85b365b293a0dbe92cf211b60228

before_script:
  - npm prune

script:
  - npm run build
  - npm run coverage

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
