language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

sudo: false

before_script:
  - npm prune

script: "gulp coverage"

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
